name: crypto_app
description: A new flutter project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3

  # Event Transformers
  stream_transform: ^2.1.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # Networking
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0
  pretty_dio_logger: ^1.3.1

  # Routing
  auto_route: ^7.3.0

  # Utility
  intl: ^0.18.0

  # UI
  ui_kit:
    path: packages/ui_kit

  # Dependency Injection
  injectable: ^2.1.1
  get_it: ^7.6.0

  # Data class generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

  # Functional programming
  dartz: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  very_good_analysis: ^5.0.0+1

  # Code Generation
  freezed: ^2.3.5
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  auto_route_generator: ^7.1.1
  injectable_generator: ^2.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
