name: cryptocurrency_tracker
description: A new flutter project

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^5.1.2
  dio_smart_retry: ^5.0.0
  pretty_dio_logger: ^1.3.1

  # Routing
  auto_route: ^7.3.0

  # Caching
  hive_flutter: ^1.1.0 
  hydrated_bloc: ^9.1.2

  # Dependency Injection
  injectable: ^2.1.1
  get_it: ^7.6.0

  # Utility
  intl: ^0.18.0
  flutter_svg: ^2.0.4
  path_provider: ^2.0.15
  stream_transform: ^2.1.0
  
  # UI
  ui_kit:
    path: packages/ui_kit

  # Data class generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

  # Functional programming
  dartz: ^0.10.1
  
  # Localization
  easy_localization: ^3.0.2

  # App icons
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linter
  very_good_analysis: ^5.0.0+1

  # Code Generation
  freezed: ^2.3.5
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  json_serializable: ^6.7.0
  auto_route_generator: ^7.1.1
  injectable_generator: ^2.1.5

  # Testing
  mocktail: ^0.3.0
  bloc_test: ^9.1.3


flutter_native_splash:
  android: true
  ios: true
  android12: true
  color: "#F8FBF8"
  image: "assets/logo/logo_no_bg.png"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_background: "#F8FBF8"
  # Padding 8%
  adaptive_icon_foreground: "assets/logo/logo_foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/logo/
    - assets/translations/
